DROP INDEX IF EXISTS idx_on_tag_id;
DROP TRIGGER IF EXISTS log_insert_tag ON tag CASCADE;
DROP TRIGGER IF EXISTS log_update_tag ON tag CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP SEQUENCE IF EXISTS tag_seq CASCADE;